-- MySQL Script generated by MySQL Workbench
-- Sat Jun 25 15:41:45 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ENCUESTA
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ENCUESTA` ;

-- -----------------------------------------------------
-- Schema ENCUESTA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ENCUESTA` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `ENCUESTA` ;

-- -----------------------------------------------------
-- Table `ENCUESTA`.`ENCUESTADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ENCUESTA`.`ENCUESTADO` (
  `idENCUESTADO` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `domicilio` VARCHAR(45) NOT NULL,
  `edad` INT NOT NULL,
  `sexo` VARCHAR(15) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`idENCUESTADO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ENCUESTA`.`CIUDAD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ENCUESTA`.`CIUDAD` (
  `idCIUDAD` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(45) NOT NULL,
  `idENCUESTADO` INT NULL,
  PRIMARY KEY (`idCIUDAD`),
  INDEX `idENCUESTADO_idx` (`idENCUESTADO` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ENCUESTA`.`PREGUNTAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ENCUESTA`.`PREGUNTAS` (
  `idPREGUNTAS` INT NOT NULL,
  `pregunta` VARCHAR(45) NOT NULL,
  `idENCUESTADO` INT NOT NULL,
  PRIMARY KEY (`idPREGUNTAS`),
  INDEX `idENCUESTADO_idx` (`idENCUESTADO` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ENCUESTA`.`PAIS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ENCUESTA`.`PAIS` (
  `idPAIS` INT NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(45) NOT NULL,
  `idCIUDAD` INT NOT NULL,
  `idENCUESTADO` INT NOT NULL,
  PRIMARY KEY (`idPAIS`),
  INDEX `idCIUDAD_idx` (`idCIUDAD` ASC) VISIBLE,
  INDEX `idENCUESTADO_idx` (`idENCUESTADO` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ENCUESTA`.`RESPUESTAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ENCUESTA`.`RESPUESTAS` (
  `idRESPUESTAS` INT NOT NULL,
  `idENCUESTA` INT NOT NULL,
  `respuesta` VARCHAR(45) NOT NULL,
  `idPREGUNTAS` INT NOT NULL,
  PRIMARY KEY (`idRESPUESTAS`),
  INDEX `idENCUESTA_idx` (`idENCUESTA` ASC) VISIBLE,
  INDEX `idPREGUNTAS_idx` (`idPREGUNTAS` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ENCUESTA`.`ENCUESTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ENCUESTA`.`ENCUESTA` (
  `idENCUESTA` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `idPREGUNTAS` INT NOT NULL,
  `idRESPUESTAS` INT NOT NULL,
  PRIMARY KEY (`idENCUESTA`),
  INDEX `idRESPUESTAS_idx` (`idRESPUESTAS` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ENCUESTA`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ENCUESTA`.`USUARIO` (
  `idUSUARIO` INT NOT NULL,
  `user` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUSUARIO`),
  UNIQUE INDEX `user_UNIQUE` (`user` ASC) VISIBLE,
  UNIQUE INDEX `clave_UNIQUE` (`clave` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ENCUESTA`.`ENCUESTADOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ENCUESTA`.`ENCUESTADOR` (
  `idENCUESTADOR` INT NOT NULL,
  `nombreencuestador` VARCHAR(45) NOT NULL,
  `domiciio` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `idUSUARIO` INT NOT NULL,
  PRIMARY KEY (`idENCUESTADOR`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ENCUESTA`.`PELICULA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ENCUESTA`.`PELICULA` (
  `idPELICULA` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `calificacion` VARCHAR(45) NOT NULL,
  `idRESPUESTAS` INT NOT NULL,
  PRIMARY KEY (`idPELICULA`),
  INDEX `idRESPUESTAS_idx` (`idRESPUESTAS` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ENCUESTA`.`CATEGORIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ENCUESTA`.`CATEGORIA` (
  `idCATEGORIA` INT NOT NULL,
  `CATEGORIA` VARCHAR(45) NOT NULL,
  `idRESPUESTAS` INT NOT NULL,
  PRIMARY KEY (`idCATEGORIA`),
  INDEX `idRESPUESTAS_idx` (`idRESPUESTAS` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ENCUESTA`.`ACTOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ENCUESTA`.`ACTOR` (
  `idACTOR` INT NOT NULL,
  `actor` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `idRESPUESTAS` INT NOT NULL,
  PRIMARY KEY (`idACTOR`),
  INDEX `idRESPUESTAS_idx` (`idRESPUESTAS` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ENCUESTA`.`PLATAFORMA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ENCUESTA`.`PLATAFORMA` (
  `idPLATAFORMA` INT NOT NULL,
  `plataforma` VARCHAR(45) NOT NULL,
  `preferencia` POINT NOT NULL,
  `idRESPUESTAS` INT NOT NULL,
  `idPAIS` INT NOT NULL,
  PRIMARY KEY (`idPLATAFORMA`),
  INDEX `idPAIS_idx` (`idPAIS` ASC) VISIBLE,
  INDEX `idRESPUESTAS_idx` (`idRESPUESTAS` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ENCUESTA`.`LENGUAGE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ENCUESTA`.`LENGUAGE` (
  `idLENGUAGE` INT NOT NULL AUTO_INCREMENT,
  `LENGUAGE` VARCHAR(45) NOT NULL,
  `idPELICULA` INT NOT NULL,
  `idrespuestas` INT NOT NULL,
  PRIMARY KEY (`idLENGUAGE`),
  INDEX `idPELICULA_idx` (`idPELICULA` ASC) VISIBLE,
  INDEX `idRESPUESTAS_idx` (`idrespuestas` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ENCUESTA`.`timestamps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ENCUESTA`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
